import "./script.js";
import "./products.js";
import "./comments.js";
import "./modal.js";
import "./form.js";
import "./car.js";
import "./cafe.js";
import "./drink.js";
import "./homework-5.js";
import "./homework-6.js";
import "./homework-7.js";
import "./homework-8.js";
// import "./homework-9.js";
import "./homework-10.js";